# Generated by Django 5.0.4 on 2024-05-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=19)),
                ('manufacturer_company_name', models.CharField(blank=True, max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('is_available_after_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('packed_height', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('packed_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('packed_length', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
